import { z } from "zod";
import { JsonValueSchema } from "../schema-core";

export const CompileIntentInputSchema = z.strictObject({
  tenantId: z.string().min(1),
  organizationId: z.string().min(1),
  principalIntentRef: z.string().min(1),
  principalId: z.string().min(1),
  agentId: z.string().min(1),
  runId: z.string().min(1),
  runtimeAdapterId: z.string().min(1),
  operatingEnvelopeId: z.string().min(1),
  toolCatalogRef: z.string().min(1),
  actionCatalogRef: z.string().min(1),
  gatewayRegistryRef: z.string().min(1),
  runtimeExecutionId: z.string().min(1).nullable().default(null),
  generatedCodeOrSpecRefs: z.array(z.string()).default([]),
  declaredAssumptions: z.array(z.string()).default([]),
  requiredEvidenceRefs: z.array(z.string()).default([]),
  candidate: z.strictObject({
    toolCapabilityId: z.string().min(1),
    actionTypeId: z.string().min(1),
    gatewayRegistryEntryId: z.string().min(1),
    actionClass: z.string().min(1),
    gatewayId: z.string().min(1),
    resourceRef: z.string().min(1),
    sequenceNumber: z.number().int().nonnegative(),
    requiredPriorActionContractIds: z.array(z.string().min(1)).default([]),
    recoveryRecommendationId: z.string().min(1).nullable().default(null),
    parameters: z.record(z.string(), JsonValueSchema),
    nonSecretParamsSummary: z.record(z.string(), JsonValueSchema),
    secretRefs: z.record(z.string(), z.string().min(1)).default({}),
    purposeCode: z.string().min(1),
    expectedSideEffectCodes: z.array(z.string().min(1)),
    evidenceRefs: z.array(z.string()).default([]),
    bounds: z.record(z.string(), JsonValueSchema).default({}),
    idempotencyKey: z.string().min(1),
    rollbackHint: z.string().max(500).nullable().default(null),
    expiresAt: z.string().datetime({ offset: true }),
  }),
  compilerVersion: z.string().min(1).default("handshake-compiler-0.2"),
});
export type CompileIntentInput = z.input<typeof CompileIntentInputSchema>;
