import { z } from "zod";
import { DigestSchema, IdSchema, IsoDateSchema, JsonValueSchema, ProtocolBaseSchema, ResourceRefSchema, SignatureSchema } from "../schema-core";
import { CredentialCustodyStatusSchema, GatewayEnforcementModeSchema, RequiredProtectedPathStateSchema } from "../catalog-envelope/schemas";
import { GeneratedExecutionCoverageStatusSchema } from "../generated-execution-graph/schemas";

export const ActionContractSchema = ProtocolBaseSchema.extend({
  actionContractId: IdSchema,
  intentCompilationId: IdSchema,
  candidateActionId: IdSchema,
  candidateDigest: DigestSchema,
  envelopeId: IdSchema,
  operatingEnvelopeDigest: DigestSchema,
  agentId: IdSchema,
  principalId: IdSchema,
  runId: IdSchema,
  runtimeAdapterId: IdSchema,
  sequenceNumber: z.number().int().nonnegative(),
  requiredPriorActionContractIds: z.array(IdSchema).default([]),
  recoveryRecommendationId: IdSchema.nullable(),
  recoverySourceReceiptId: IdSchema.nullable(),
  recoveryRecommendationDigest: DigestSchema.nullable(),
  issuedAt: IsoDateSchema,
  expiresAt: IsoDateSchema,
  gatewayRegistryEntryId: IdSchema,
  gatewayRegistryDigest: DigestSchema,
  gatewayRegistryVersion: z.string().min(1),
  gatewayId: IdSchema,
  gatewayPolicyContractId: IdSchema,
  gatewayPolicyVersion: z.string().min(1),
  credentialCustodyStatus: CredentialCustodyStatusSchema,
  enforcementMode: GatewayEnforcementModeSchema,
  mutationCredentialHolderRef: z.string().min(1),
  gatewayAuthorityHolderRef: z.string().min(1),
  toolCapabilityId: IdSchema,
  toolCapabilityDigest: DigestSchema,
  actionTypeId: IdSchema,
  actionTypeDigest: DigestSchema,
  actionClass: z.string().min(1),
  protectedSurfaceKind: z.string().min(1),
  resourceRef: ResourceRefSchema,
  requiredProtectedPathState: RequiredProtectedPathStateSchema,
  runtimeExecutionId: IdSchema.nullable(),
  runtimeExecutionDigest: DigestSchema.nullable(),
  generatedExecutionGraphId: IdSchema.nullable().default(null),
  generatedExecutionGraphDigest: DigestSchema.nullable().default(null),
  generatedExecutionCoverageStatus: GeneratedExecutionCoverageStatusSchema.nullable().default(null),
  generatedExecutionNodeId: IdSchema.nullable().default(null),
  generatedExecutionNodeDigest: DigestSchema.nullable().default(null),
  generatedExecutionCatalogSnapshotDigest: DigestSchema.nullable().default(null),
  generatedExecutionGatewayRegistrySnapshotDigest: DigestSchema.nullable().default(null),
  generatedExecutionRegistryBindingSetDigest: DigestSchema.nullable().default(null),
  generatedExecutionNodeGatewayBindingDigest: DigestSchema.nullable().default(null),
  parameters: z.record(z.string(), JsonValueSchema),
  paramsDigest: DigestSchema,
  nonSecretParamsSummary: z.record(z.string(), JsonValueSchema),
  secretRefs: z.record(z.string(), z.string().min(1)).default({}),
  purposeCode: z.string().min(1),
  expectedSideEffectCodes: z.array(z.string().min(1)),
  evidenceRefs: z.array(z.string()).default([]),
  bounds: z.record(z.string(), JsonValueSchema).default({}),
  idempotencyKey: IdSchema,
  rollbackHint: z.string().max(500).nullable(),
  canonicalizerVersion: z.string().min(1),
  actionContractDigest: DigestSchema,
  contractSignature: SignatureSchema.nullable(),
});
export type ActionContract = z.infer<typeof ActionContractSchema>;
