import type { OperationReadbackProjection } from "../../src/protocol/evidence-projections/schemas";

const digest = (byte: string) => `sha256:${byte.repeat(64)}` as const;

export function sampleOperationReadbackProjection(
  overrides: Partial<OperationReadbackProjection> = {},
): OperationReadbackProjection {
  const actionContractRef = overrides.actionContractRef ?? "act_readback_demo";
  return {
    schemaVersion: "handshake.operation-readback.v0.1",
    actionContractRef,
    contractDigest: digest("1"),
    principalRef: "principal_demo",
    agentRef: "agent_demo",
    runId: "run_demo",
    runtimeAdapterRef: "adapter_demo",
    actionClass: "x402_payment.exact",
    protectedSurfaceKind: "wallet_gateway",
    resourceRef: "resource:demo",
    gatewayId: "gateway_demo",
    gatewayPolicyVersion: "v0",
    sourceAuthority: "protocol_store_projection",
    operationStatus: "downstream_succeeded",
    latestAuthoritativeStage: "receipt",
    policyDecisionRef: "policy_demo",
    policyDecisionStatus: "greenlight",
    agreementObligationPolicy: {
      sourceAuthority: "policy_decision_snapshot",
      evaluationStatus: "greenlight",
      ok: true,
      reasonCode: null,
      reason: null,
      policyInput: {
        posture: "not_applicable",
        obligationRef: null,
        linkedAgreementId: null,
        acceptedNegotiationResolutionId: null,
      },
    },
    greenlightRef: "green_demo",
    gateAttemptRef: "gate_demo",
    mutationAttemptRef: "mutation_demo",
    receiptRef: "receipt_demo",
    gatewayAdmissionStatus: "admitted",
    downstreamOutcomeStatus: "succeeded",
    finalityStatus: "final",
    greenlightUsePosture: "consumed",
    reasonCodes: [],
    nextMechanism: "read_evidence",
    safeToRetryReadback: true,
    safeToReuseGreenlight: false,
    requiresNewContract: false,
    authorityCreatedByReadback: false,
    greenlightCreatedByReadback: false,
    gatewayCheckPerformedByReadback: false,
    mutationAttemptedByReadback: false,
    receiptExportCreatedByReadback: false,
    rawInternalRecordIncluded: false,
    credentialMaterialIncluded: false,
    paymentMaterialIncluded: false,
    evidenceRefs: ["evidence:readback:demo"],
    proofGapRefs: [],
    refusalRefs: [],
    recoveryRefs: [],
    isolationRefs: [],
    authorityCertificateRefs: [],
    providerRequestRef: null,
    providerOperationRef: null,
    traceRef: null,
    spanRef: null,
    redactionProfileRef: "operation-readback:v0.1-redacted",
    omittedFields: [],
    supportContext: {
      schemaVersion: "handshake.support-context.v0.1",
      supportContextRef: "support:readback:demo",
      sourceAuthority: "protocol_store_projection",
      surface: "operation_readback",
      actionContractRef,
      requestIdentity: null,
      operationStatus: "downstream_succeeded",
      reasonCodes: [],
      nextMechanism: "read_evidence",
      safeToRetryReadback: true,
      safeToReuseGreenlight: false,
      requiresNewContract: false,
      supportSeverity: "none",
      docsUrl: null,
      nextCommand: "handshake evidence fetch --contract-id act_readback_demo",
      evidenceRefs: [],
      proofGapRefs: [],
      refusalRefs: [],
      traceRef: null,
      spanRef: null,
      redactionProfileRef: "operation-readback:v0.1-redacted",
    },
    ...overrides,
  };
}
