export const surfaceBoundaryManifestVersion = "surface-boundary.v0.1" as const;

export const surfaceIds = [
  "sdk.runtime",
  "sdk.evidence",
  "sdk.control_plane",
  "sdk.policy",
  "sdk.adapter",
  "sdk.install",
  "sdk.gateway",
  "cli.operator",
  "cli.evidence",
  "cli.process",
  "mcp.runtime",
  "x402.protected_tool",
  "surfaces.a2a_negotiation",
  "surfaces.a2a_readback",
  "surfaces.service_workflow_admission",
  "surfaces.hosted_admission",
] as const;

export type SurfaceId = (typeof surfaceIds)[number];

export const surfaceRouteFamilies = [
  "action_contract_proposal_write",
  "adapter_definition_write",
  "bypass_probe_write",
  "catalog_install_write",
  "certificate_mint_write",
  "certificate_verify_local",
  "delegated_authority_write",
  "evidence_projection_read",
  "gateway_credential_write",
  "gateway_check_write",
  "install_health_read",
  "install_proposal_shape_read",
  "isolation_write",
  "local_process_supervision",
  "policy_decision_write",
  "protected_path_posture_write",
  "raw_record_read",
  "receipt_export_write",
  "recovery_write",
  "runtime_evidence_write",
  "runtime_ingress_proposal_write",
  "surface_reconciliation_write",
  "tool_call_draft_write",
] as const;

export type SurfaceRouteFamily = (typeof surfaceRouteFamilies)[number];

export const surfaceCustodyRoles = [
  "control_plane",
  "gateway_custody",
  "review_custody",
  "runtime_evidence",
  "none",
] as const;

export type SurfaceCustodyRole = (typeof surfaceCustodyRoles)[number];

export const surfacePlanes = ["runtime", "evidence", "operator", "gateway", "process"] as const;

export type SurfacePlane = (typeof surfacePlanes)[number];

export const surfaceImplementationStatuses = ["active", "deferred"] as const;

export type SurfaceImplementationStatus = (typeof surfaceImplementationStatuses)[number];

export const surfaceAuthorityPostures = [
  "proposal_only",
  "evidence_only",
  "setup_only",
  "transport_only",
  "policy_transition_transport",
] as const;

export type SurfaceAuthorityPosture = (typeof surfaceAuthorityPostures)[number];

export const surfaceNonAuthorityFlags = [
  "authorityCreated",
  "credentialMaterialIncluded",
  "gatewayCheckPerformed",
  "greenlightCreated",
  "mutationAttempted",
  "mutationCommandIncluded",
  "rawInternalRecordIncluded",
  "receiptExportCreated",
  "authorityCertificateMinted",
] as const;

export type SurfaceNonAuthorityFlag = (typeof surfaceNonAuthorityFlags)[number];

export type SurfaceBoundary = {
  readonly id: SurfaceId;
  readonly status: SurfaceImplementationStatus;
  readonly plane: SurfacePlane;
  readonly custodyRole: SurfaceCustodyRole;
  readonly authorityPosture: SurfaceAuthorityPosture;
  readonly sourceRoots: readonly string[];
  readonly allowedRouteFamilies: readonly SurfaceRouteFamily[];
  readonly forbiddenRouteFamilies: readonly SurfaceRouteFamily[];
  readonly allowedImportRoots: readonly string[];
  readonly forbiddenImportFragments: readonly string[];
  readonly forbiddenCredentialShapes: readonly string[];
  readonly forbiddenOutputFields: readonly string[];
  readonly requiredNonAuthorityFlags: Readonly<Partial<Record<SurfaceNonAuthorityFlag, false>>>;
  readonly claimBoundaryLabels: readonly string[];
};

type SdkSurfaceId = Extract<SurfaceId, `sdk.${string}`>;
type CliSurfaceId = Extract<SurfaceId, `cli.${string}`>;
type RuntimeAdapterSurfaceId = Extract<SurfaceId, "mcp.runtime" | "x402.protected_tool">;

const forbiddenAuthorityRouteFamilies = [
  "certificate_mint_write",
  "isolation_write",
  "policy_decision_write",
  "raw_record_read",
  "receipt_export_write",
  "recovery_write",
] as const satisfies readonly SurfaceRouteFamily[];

const forbiddenAuthorityImports = [
  "protocol/kernel",
  "protocol/areas/policy-greenlight/guards",
  "protocol/areas/policy-greenlight/policy",
  "protocol/areas/policy-greenlight/policy-record",
  "protocol/areas/policy-greenlight/sequence-dependencies",
  "protocol/areas/policy-greenlight/transitions",
  "protocol/areas/gateway-gate/artifacts",
  "protocol/areas/gateway-gate/gateway-policy",
  "protocol/areas/gateway-gate/guards",
  "protocol/areas/gateway-gate/replay-refusal",
  "protocol/areas/gateway-gate/transitions",
  "protocol/areas/receipt-export/transitions",
  "protocol/areas/authority-certificate/signing",
  "protocol/areas/authority-certificate/transitions",
  "storage/",
  "adapters/x402-payment/wallet-gateway",
  "experimental",
] as const;

const authorityCredentialShapes = [
  "allRoles",
  "CallerAuthTokens",
  "transitionToken",
  "transitionTokens",
  "control_plane_token",
  "gateway_custody_token",
  "private_key",
  "signer",
  "wallet",
] as const;

const authorityOutputFields = [
  "PaymentPayload",
  "PAYMENT-SIGNATURE",
  "authorityCertificateMint",
  "gatewayCheckInput",
  "mutationCommand",
  "privateKey",
  "rawCredentialMaterial",
  "rawInternalRecord",
  "receiptExport",
  "signer",
] as const;

const cliAuthorityOutputFields = authorityOutputFields.filter((field) => !["privateKey", "signer"].includes(field));

const proposalNonAuthorityFlags = {
  authorityCreated: false,
  authorityCertificateMinted: false,
  credentialMaterialIncluded: false,
  gatewayCheckPerformed: false,
  greenlightCreated: false,
  mutationAttempted: false,
  mutationCommandIncluded: false,
  rawInternalRecordIncluded: false,
  receiptExportCreated: false,
} as const;

const evidenceNonAuthorityFlags = {
  authorityCreated: false,
  authorityCertificateMinted: false,
  credentialMaterialIncluded: false,
  gatewayCheckPerformed: false,
  greenlightCreated: false,
  mutationAttempted: false,
  mutationCommandIncluded: false,
  rawInternalRecordIncluded: false,
  receiptExportCreated: false,
} as const;

const sharedClaimBoundaries = [
  "local_or_self_hosted_only",
  "no_broad_runtime_control",
  "no_clearing_house_operation",
  "no_cross_org_trust",
  "no_hosted_operation",
  "no_provider_custody",
  "no_settlement_claim",
] as const;

const sdkSurfaceBoundaryManifest = {
  "sdk.runtime": {
    id: "sdk.runtime",
    status: "active",
    plane: "runtime",
    custodyRole: "runtime_evidence",
    authorityPosture: "proposal_only",
    sourceRoots: ["src/sdk/surface-clients/runtime-client.ts", "src/sdk/surface-clients/transport.ts"],
    allowedRouteFamilies: [
      "runtime_evidence_write",
      "runtime_ingress_proposal_write",
      "tool_call_draft_write",
      "action_contract_proposal_write",
    ],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "protected_path_posture_write",
      "surface_reconciliation_write",
    ],
    allowedImportRoots: ["src/sdk", "src/runtime", "src/protocol/public", "src/protocol/foundation/errors", "src/http/errors", "src/http/admission"],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "protocol/areas/gateway-gate/"],
    forbiddenCredentialShapes: [...authorityCredentialShapes, "review_custody_token"],
    forbiddenOutputFields: [...cliAuthorityOutputFields, "greenlightId", "greenlightRef", "gatewayCheckInput"],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "runtime_evidence_is_not_authority"],
  },
  "sdk.evidence": {
    id: "sdk.evidence",
    status: "active",
    plane: "evidence",
    custodyRole: "review_custody",
    authorityPosture: "evidence_only",
    sourceRoots: ["src/sdk/surface-clients/evidence-client.ts", "src/sdk/surface-clients/transport.ts"],
    allowedRouteFamilies: ["evidence_projection_read", "install_health_read", "certificate_verify_local"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "protected_path_posture_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: [
      "src/sdk",
      "src/protocol/public",
      "src/protocol/areas/authority-certificate/verify",
      "src/protocol/foundation/errors",
      "src/http/errors",
      "src/http/admission",
    ],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "protocol/store"],
    forbiddenCredentialShapes: [
      ...authorityCredentialShapes.filter((shape) => shape !== "control_plane_token"),
      "runtime_evidence_write_token",
    ],
    forbiddenOutputFields: [...cliAuthorityOutputFields, "downstreamSuccess"],
    requiredNonAuthorityFlags: evidenceNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "evidence_is_not_downstream_success"],
  },
  "sdk.control_plane": {
    id: "sdk.control_plane",
    status: "active",
    plane: "operator",
    custodyRole: "control_plane",
    authorityPosture: "setup_only",
    sourceRoots: ["src/sdk/surface-clients/control-plane-client.ts", "src/sdk/surface-clients/transport.ts"],
    allowedRouteFamilies: ["delegated_authority_write"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "protected_path_posture_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: ["src/sdk", "src/protocol/public", "src/protocol/foundation/errors", "src/http/errors", "src/http/admission"],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [
      "allRoles",
      "CallerAuthTokens",
      "gateway_custody_token",
      "private_key",
      "runtime_evidence_token",
      "signer",
      "transitionTokens",
      "wallet",
    ],
    forbiddenOutputFields: [...authorityOutputFields, "greenlightId", "greenlightRef", "gatewayCheckInput"],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "delegation_management_is_not_execution_authority"],
  },
  "sdk.policy": {
    id: "sdk.policy",
    status: "active",
    plane: "operator",
    custodyRole: "control_plane",
    authorityPosture: "policy_transition_transport",
    sourceRoots: ["src/sdk/surface-clients/policy-client.ts", "src/sdk/surface-clients/transport.ts"],
    allowedRouteFamilies: ["policy_decision_write"],
    forbiddenRouteFamilies: [
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "certificate_mint_write",
      "evidence_projection_read",
      "gateway_check_write",
      "install_health_read",
      "isolation_write",
      "local_process_supervision",
      "protected_path_posture_write",
      "raw_record_read",
      "receipt_export_write",
      "recovery_write",
      "runtime_evidence_write",
      "runtime_ingress_proposal_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: ["src/sdk", "src/protocol/public", "src/protocol/foundation/errors", "src/http/errors", "src/http/admission"],
    forbiddenImportFragments: [
      "adapters/",
      "experimental",
      "protocol/areas/authority-certificate/",
      "protocol/areas/gateway-gate/",
      "protocol/areas/policy-greenlight/",
      "protocol/areas/receipt-export/",
      "storage/",
    ],
    forbiddenCredentialShapes: [
      "allRoles",
      "CallerAuthTokens",
      "gateway_custody_token",
      "private_key",
      "runtime_evidence_token",
      "signer",
      "transitionTokens",
      "wallet",
    ],
    forbiddenOutputFields: [
      "PaymentPayload",
      "PAYMENT-SIGNATURE",
      "authorityCertificateMint",
      "gatewayCheckInput",
      "mutationCommand",
      "privateKey",
      "rawCredentialMaterial",
      "rawInternalRecord",
      "receiptExport",
      "signer",
    ],
    requiredNonAuthorityFlags: {
      authorityCertificateMinted: false,
      credentialMaterialIncluded: false,
      gatewayCheckPerformed: false,
      mutationAttempted: false,
      mutationCommandIncluded: false,
      rawInternalRecordIncluded: false,
      receiptExportCreated: false,
    },
    claimBoundaryLabels: [...sharedClaimBoundaries, "policy_transition_transport_is_not_gateway_execution"],
  },
  "sdk.adapter": {
    id: "sdk.adapter",
    status: "active",
    plane: "operator",
    custodyRole: "none",
    authorityPosture: "setup_only",
    sourceRoots: ["src/adapter-sdk"],
    allowedRouteFamilies: ["adapter_definition_write", "install_proposal_shape_read"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "certificate_verify_local",
      "evidence_projection_read",
      "gateway_check_write",
      "install_health_read",
      "local_process_supervision",
      "protected_path_posture_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: ["src/adapter-sdk", "src/install"],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "experimental", "runtime/", "storage/"],
    forbiddenCredentialShapes: [...authorityCredentialShapes, "review_custody_token", "runtime_evidence_write_token"],
    forbiddenOutputFields: [...authorityOutputFields, "greenlightId", "greenlightRef"],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "adapter_sdk_is_definition_only"],
  },
  "sdk.install": {
    id: "sdk.install",
    status: "active",
    plane: "operator",
    custodyRole: "control_plane",
    authorityPosture: "setup_only",
    sourceRoots: ["src/sdk/surface-clients/install-client.ts", "src/sdk/surface-clients/transport.ts"],
    allowedRouteFamilies: ["catalog_install_write"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "gateway_check_write",
      "protected_path_posture_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: ["src/sdk", "src/install", "src/protocol/public", "src/protocol/foundation/errors", "src/http/errors", "src/http/admission"],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [
      "allRoles",
      "CallerAuthTokens",
      "gateway_custody_token",
      "private_key",
      "runtime_evidence_token",
      "signer",
      "transitionTokens",
      "wallet",
    ],
    forbiddenOutputFields: authorityOutputFields,
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "install_is_not_permission"],
  },
  "sdk.gateway": {
    id: "sdk.gateway",
    status: "active",
    plane: "gateway",
    custodyRole: "gateway_custody",
    authorityPosture: "transport_only",
    sourceRoots: ["src/sdk/surface-clients/gateway-client.ts", "src/sdk/surface-clients/transport.ts"],
    allowedRouteFamilies: [
      "bypass_probe_write",
      "gateway_credential_write",
      "gateway_check_write",
      "protected_path_posture_write",
      "surface_reconciliation_write",
    ],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "catalog_install_write",
      "runtime_evidence_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: ["src/sdk", "src/protocol/public", "src/protocol/foundation/errors", "src/http/errors", "src/http/admission"],
    forbiddenImportFragments: [
      "adapters/x402-payment/wallet-gateway",
      "experimental",
      "protocol/areas/authority-certificate/signing",
      "protocol/areas/authority-certificate/transitions",
      "protocol/areas/policy-greenlight/",
      "storage/",
    ],
    forbiddenCredentialShapes: [
      "allRoles",
      "CallerAuthTokens",
      "control_plane_token",
      "private_key",
      "runtime_evidence_token",
      "signer_factory",
      "transitionTokens",
    ],
    forbiddenOutputFields: [
      "PaymentPayload",
      "PAYMENT-SIGNATURE",
      "privateKey",
      "rawCredentialMaterial",
      "rawInternalRecord",
      "signerFactory",
    ],
    requiredNonAuthorityFlags: {
      authorityCertificateMinted: false,
      credentialMaterialIncluded: false,
      rawInternalRecordIncluded: false,
      receiptExportCreated: false,
    },
    claimBoundaryLabels: [...sharedClaimBoundaries, "gateway_transport_is_not_signer_custody"],
  },
} as const satisfies Record<SdkSurfaceId, SurfaceBoundary>;

const cliSurfaceBoundaryManifest = {
  "cli.operator": {
    id: "cli.operator",
    status: "active",
    plane: "operator",
    custodyRole: "control_plane",
    authorityPosture: "setup_only",
    sourceRoots: [
      "src/cli/command-manifest.ts",
      "src/cli/demo/x402.ts",
      "src/cli/host/doctor.ts",
      "src/cli/local-project/doctor.ts",
      "src/cli/local-project/index.ts",
      "src/cli/main.ts",
      "src/cli/mcp/doctor.ts",
      "src/cli/output.ts",
      "src/cli/quickstart/x402.ts",
      "src/cli/state/inspect.ts",
      "src/cli/x402/index.ts",
      "src/cli/x402/local-state.ts",
      "src/cli/x402/readiness.ts",
    ],
    allowedRouteFamilies: ["catalog_install_write", "install_health_read"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "gateway_check_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: [
      "src/cli",
      "src/adapters/x402-payment/bypass-probes",
      "src/adapters/x402-payment/conformance",
      "src/adapters/x402-payment/install-proposal",
      "src/adapters/x402-payment/protected-tool-profile",
      "src/adapters/x402-payment/protected-tool-readiness",
      "src/install/install-proposal",
      "src/mcp",
      "src/protocol/areas/bypass-probe",
      "src/protocol/evidence-projections",
      "src/protocol/foundation",
      "src/surfaces",
    ],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "wallet-gateway", "storage/"],
    forbiddenCredentialShapes: [
      "allRoles",
      "CallerAuthTokens",
      "gateway_custody_token",
      "runtime_evidence_token",
      "transitionTokens",
    ],
    forbiddenOutputFields: [...cliAuthorityOutputFields, "greenlightId", "greenlightRef", "gatewayCheckInput"],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "operator_setup_is_not_authorization"],
  },
  "cli.evidence": {
    id: "cli.evidence",
    status: "active",
    plane: "evidence",
    custodyRole: "review_custody",
    authorityPosture: "evidence_only",
    sourceRoots: [
      "src/cli/aps-report.ts",
      "src/cli/certificate.ts",
      "src/cli/command-manifest.ts",
      "src/cli/evidence/operation-readback-view.ts",
      "src/cli/main.ts",
      "src/cli/output.ts",
      "src/cli/projection-evidence.ts",
      "src/cli/quality/report.ts",
      "src/cli/simulate/x402-payment.ts",
      "src/cli/support-bundle.ts",
    ],
    allowedRouteFamilies: ["certificate_verify_local", "evidence_projection_read", "install_health_read"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "catalog_install_write",
      "gateway_check_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: [
      "src/cli",
      "src/hosted-admission",
      "src/mcp",
      "src/protocol/areas/authority-certificate/verify",
      "src/protocol/evidence-projections",
      "src/protocol/public",
      "src/surfaces",
    ],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [
      "allRoles",
      "CallerAuthTokens",
      "control_plane_token",
      "gateway_custody_token",
      "transitionTokens",
    ],
    forbiddenOutputFields: [...cliAuthorityOutputFields, "downstreamSuccess"],
    requiredNonAuthorityFlags: evidenceNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "cli_evidence_is_not_clearance"],
  },
  "cli.process": {
    id: "cli.process",
    status: "deferred",
    plane: "process",
    custodyRole: "none",
    authorityPosture: "transport_only",
    sourceRoots: ["src/cli/process"],
    allowedRouteFamilies: ["local_process_supervision"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "catalog_install_write",
      "gateway_check_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: ["src/cli", "src/sdk", "src/surfaces"],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [...authorityCredentialShapes],
    forbiddenOutputFields: [...cliAuthorityOutputFields, "greenlightId", "greenlightRef", "gatewayCheckInput"],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "process_start_is_not_gateway_custody"],
  },
} as const satisfies Record<CliSurfaceId, SurfaceBoundary>;

const runtimeSurfaceBoundaryManifest = {
  "mcp.runtime": {
    id: "mcp.runtime",
    status: "active",
    plane: "runtime",
    custodyRole: "runtime_evidence",
    authorityPosture: "proposal_only",
    sourceRoots: ["src/mcp"],
    allowedRouteFamilies: [
      "action_contract_proposal_write",
      "evidence_projection_read",
      "install_health_read",
      "runtime_evidence_write",
      "tool_call_draft_write",
    ],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "protected_path_posture_write",
      "surface_reconciliation_write",
    ],
    allowedImportRoots: ["src/mcp", "src/protocol/evidence-projections", "src/protocol/foundation/failure-class", "src/sdk", "src/surfaces"],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [...authorityCredentialShapes, "review_custody_token"],
    forbiddenOutputFields: [
      ...authorityOutputFields,
      "greenlightId",
      "gatewayCheckInput",
      "mutationCommand",
      "mutationAttemptId",
    ],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [...sharedClaimBoundaries, "tool_visibility_is_not_authorization"],
  },
  "x402.protected_tool": {
    id: "x402.protected_tool",
    status: "active",
    plane: "runtime",
    custodyRole: "runtime_evidence",
    authorityPosture: "proposal_only",
    sourceRoots: ["src/x402-protected-tool"],
    allowedRouteFamilies: [
      "action_contract_proposal_write",
      "evidence_projection_read",
      "install_health_read",
      "runtime_evidence_write",
      "tool_call_draft_write",
    ],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "protected_path_posture_write",
      "surface_reconciliation_write",
    ],
    allowedImportRoots: [
      "src/x402-protected-tool",
      "src/adapters/x402-payment/protected-tool-facade",
      "src/adapters/x402-payment/protected-tool-profile",
      "src/adapters/x402-payment/protected-tool-readiness",
      "src/surfaces",
    ],
    forbiddenImportFragments: [
      ...forbiddenAuthorityImports,
      "adapters/x402-payment/wallet-gateway",
      "protocol/areas/gateway-gate/",
      "storage/",
    ],
    forbiddenCredentialShapes: [...authorityCredentialShapes, "review_custody_token"],
    forbiddenOutputFields: [
      ...authorityOutputFields,
      "greenlightId",
      "gatewayCheckInput",
      "mutationCommand",
      "mutationAttemptId",
    ],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [
      ...sharedClaimBoundaries,
      "protected_tool_readiness_is_pre_contract",
      "x402_tool_profile_is_not_gateway_custody",
      "tool_visibility_is_not_authorization",
    ],
  },
} as const satisfies Record<RuntimeAdapterSurfaceId, SurfaceBoundary>;

const productSurfaceBoundaryManifest = {
  "surfaces.a2a_negotiation": {
    id: "surfaces.a2a_negotiation",
    status: "active",
    plane: "runtime",
    custodyRole: "runtime_evidence",
    authorityPosture: "evidence_only",
    sourceRoots: ["src/surfaces/a2a-negotiation-support"],
    allowedRouteFamilies: ["evidence_projection_read", "runtime_evidence_write"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "gateway_credential_write",
      "protected_path_posture_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: [
      "src/surfaces/a2a-negotiation-support",
      "src/protocol/areas/action-contract",
      "src/protocol/areas/negotiation",
      "src/protocol/areas/policy-greenlight",
      "src/protocol/evidence-projections",
      "src/protocol/foundation",
      "src/protocol/public",
      "src/protocol/store/port",
    ],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/x402-payment/wallet-gateway", "storage/"],
    forbiddenCredentialShapes: [
      ...authorityCredentialShapes.filter((shape) => shape !== "signer"),
      "review_custody_token",
    ],
    forbiddenOutputFields: [
      ...cliAuthorityOutputFields,
      "greenlightId",
      "greenlightRef",
      "gatewayCheckInput",
      "mutationCommand",
    ],
    requiredNonAuthorityFlags: evidenceNonAuthorityFlags,
    claimBoundaryLabels: [
      ...sharedClaimBoundaries,
      "admission_readback_is_not_receipt_evidence",
      "agreement_is_not_permission",
      "a2a_ingress_admission_is_not_policy_or_gateway",
    ],
  },
  "surfaces.a2a_readback": {
    id: "surfaces.a2a_readback",
    status: "active",
    plane: "evidence",
    custodyRole: "review_custody",
    authorityPosture: "evidence_only",
    sourceRoots: ["src/surfaces/a2a-negotiation-readback"],
    allowedRouteFamilies: ["evidence_projection_read", "install_health_read"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: [
      "src/surfaces/a2a-negotiation-readback",
      "src/protocol/public",
      "src/protocol/foundation",
      "src/protocol/evidence-projections",
    ],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [
      ...authorityCredentialShapes.filter((shape) => shape !== "signer"),
      "signerMaterialIncluded",
    ],
    forbiddenOutputFields: [...cliAuthorityOutputFields.filter((field) => field !== "signer"), "downstreamSuccess"],
    requiredNonAuthorityFlags: evidenceNonAuthorityFlags,
    claimBoundaryLabels: [
      ...sharedClaimBoundaries,
      "gateway_check_remains_final_enforcement_point",
      "agreement_evidence_is_not_downstream_success",
      "admission_readback_is_not_receipt_evidence",
    ],
  },
  "surfaces.service_workflow_admission": {
    id: "surfaces.service_workflow_admission",
    status: "active",
    plane: "evidence",
    custodyRole: "review_custody",
    authorityPosture: "evidence_only",
    sourceRoots: ["src/surfaces/service-workflow-admission"],
    allowedRouteFamilies: ["evidence_projection_read", "install_health_read"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: [
      "src/surfaces/service-workflow-admission",
      "src/protocol/public",
      "src/protocol/foundation",
    ],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [...authorityCredentialShapes],
    forbiddenOutputFields: [...cliAuthorityOutputFields, "downstreamSuccess"],
    requiredNonAuthorityFlags: evidenceNonAuthorityFlags,
    claimBoundaryLabels: [
      ...sharedClaimBoundaries,
      "admission_readback_is_not_receipt_evidence",
      "service_workflow_handle_is_not_clearance",
      "fresh_action_contract_required",
    ],
  },
  "surfaces.hosted_admission": {
    id: "surfaces.hosted_admission",
    status: "active",
    plane: "operator",
    custodyRole: "control_plane",
    authorityPosture: "setup_only",
    sourceRoots: ["src/hosted-admission"],
    allowedRouteFamilies: ["evidence_projection_read", "install_health_read"],
    forbiddenRouteFamilies: [
      ...forbiddenAuthorityRouteFamilies,
      "action_contract_proposal_write",
      "bypass_probe_write",
      "catalog_install_write",
      "gateway_check_write",
      "gateway_credential_write",
      "runtime_evidence_write",
      "surface_reconciliation_write",
      "tool_call_draft_write",
    ],
    allowedImportRoots: [
      "src/hosted-admission",
      "src/protocol/context",
      "src/protocol/foundation",
      "src/protocol/public",
      "src/protocol/foundation/errors",
      "src/http/errors",
    ],
    forbiddenImportFragments: [...forbiddenAuthorityImports, "adapters/", "storage/"],
    forbiddenCredentialShapes: [
      "allRoles",
      "CallerAuthTokens",
      "gateway_custody_token",
      "private_key",
      "signer",
      "transitionTokens",
      "wallet",
    ],
    forbiddenOutputFields: [...cliAuthorityOutputFields, "greenlightId", "greenlightRef", "gatewayCheckInput"],
    requiredNonAuthorityFlags: proposalNonAuthorityFlags,
    claimBoundaryLabels: [
      ...sharedClaimBoundaries,
      "hosted_admission_package_is_not_http_internals",
      "hosted_caller_identity_is_not_reusable_auth",
      "verifier_adapter_claim_is_not_gateway_check",
    ],
  },
} as const satisfies Record<
  Extract<
    SurfaceId,
    | "surfaces.a2a_negotiation"
    | "surfaces.a2a_readback"
    | "surfaces.service_workflow_admission"
    | "surfaces.hosted_admission"
  >,
  SurfaceBoundary
>;

export const surfaceBoundaryManifest = {
  ...sdkSurfaceBoundaryManifest,
  ...cliSurfaceBoundaryManifest,
  ...runtimeSurfaceBoundaryManifest,
  ...productSurfaceBoundaryManifest,
} as const satisfies Record<SurfaceId, SurfaceBoundary>;
