import { z } from "zod";
import { DigestSchema } from "../../foundation/schema-core";
import {
  CredentialResolutionEvidenceSchema,
  GatewayCredentialRefSchema,
  CredentialResolutionRedactionStatusSchema,
  CredentialResolutionResultClassSchema,
  GatewayCustodyProofPacketSchema,
} from "./schemas";

export const RegisterGatewayCredentialRefInputSchema = z.strictObject({
  tenantId: z.string().min(1),
  organizationId: z.string().min(1),
  gatewayCredentialRefId: z.string().min(1).optional(),
  principalId: z.string().min(1).nullable().default(null),
  gatewayId: z.string().min(1),
  gatewayRegistryEntryId: z.string().min(1),
  protectedSurfaceKind: z.string().min(1),
  actionClasses: z.array(z.string().min(1)).min(1),
  resourceRefs: GatewayCredentialRefSchema.shape.resourceRefs,
  resourceNamespaceRef: z.string().min(1),
  credentialKind: GatewayCredentialRefSchema.shape.credentialKind,
  custodyStatus: GatewayCredentialRefSchema.shape.custodyStatus,
  providerClass: GatewayCredentialRefSchema.shape.providerClass,
  providerRegistryRef: GatewayCredentialRefSchema.shape.providerRegistryRef,
  providerRegistryDigest: DigestSchema.nullable().default(null),
  resolverRef: GatewayCredentialRefSchema.shape.resolverRef,
  resolverVersion: z.string().min(1),
  evidenceExpectationRefs: GatewayCredentialRefSchema.shape.evidenceExpectationRefs,
  issuedAt: z.string().datetime({ offset: true }).optional(),
  expiresAt: z.string().datetime({ offset: true }).nullable().default(null),
});
export type RegisterGatewayCredentialRefInput = z.input<typeof RegisterGatewayCredentialRefInputSchema>;

export const RecordCredentialResolutionEvidenceInputSchema = z.strictObject({
  actionContractId: z.string().min(1),
  greenlightId: z.string().min(1),
  gateAttemptId: z.string().min(1),
  gatewayCredentialRefId: z.string().min(1),
  gatewayCredentialRefDigest: DigestSchema,
  requestDigest: DigestSchema,
  resultClass: CredentialResolutionResultClassSchema,
  resultReasonCode: z.string().min(2),
  redactionStatus: CredentialResolutionRedactionStatusSchema,
  providerRequestRef: CredentialResolutionEvidenceSchema.shape.providerRequestRef,
  providerOperationRef: CredentialResolutionEvidenceSchema.shape.providerOperationRef,
  proofGapId: z.string().min(1).nullable().default(null),
  refusalId: z.string().min(1).nullable().default(null),
  evidenceRefs: CredentialResolutionEvidenceSchema.shape.evidenceRefs,
  recordedAt: z.string().datetime({ offset: true }).optional(),
});
export type RecordCredentialResolutionEvidenceInput = z.input<typeof RecordCredentialResolutionEvidenceInputSchema>;

export const RecordGatewayCustodyProofPacketInputSchema = z.strictObject({
  tenantId: z.string().min(1),
  organizationId: z.string().min(1),
  gatewayCustodyProofPacketId: z.string().min(1).optional(),
  gatewayCredentialRefId: z.string().min(1),
  gatewayCredentialRefDigest: DigestSchema,
  protectedPathPostureId: z.string().min(1),
  protectedPathPostureDigest: DigestSchema,
  gatewayInstallEvidenceRefs: GatewayCustodyProofPacketSchema.shape.gatewayInstallEvidenceRefs,
  gatewayInstallEvidenceDigests: GatewayCustodyProofPacketSchema.shape.gatewayInstallEvidenceDigests,
  bypassProbeIds: GatewayCustodyProofPacketSchema.shape.bypassProbeIds,
  bypassProbeDigests: GatewayCustodyProofPacketSchema.shape.bypassProbeDigests,
  custodyClaimLevel: GatewayCustodyProofPacketSchema.shape.custodyClaimLevel,
  custodyProviderClass: GatewayCustodyProofPacketSchema.shape.custodyProviderClass,
  custodyProviderRegistryRef: GatewayCustodyProofPacketSchema.shape.custodyProviderRegistryRef,
  custodyProviderRegistryDigest: GatewayCustodyProofPacketSchema.shape.custodyProviderRegistryDigest,
  opaqueKeyHandleRef: GatewayCustodyProofPacketSchema.shape.opaqueKeyHandleRef,
  opaqueKeyHandleDigest: GatewayCustodyProofPacketSchema.shape.opaqueKeyHandleDigest,
  leaseRef: GatewayCustodyProofPacketSchema.shape.leaseRef,
  leaseVersion: GatewayCustodyProofPacketSchema.shape.leaseVersion,
  leaseIssuedAt: GatewayCustodyProofPacketSchema.shape.leaseIssuedAt,
  leaseExpiresAt: GatewayCustodyProofPacketSchema.shape.leaseExpiresAt,
  attestationRefs: GatewayCustodyProofPacketSchema.shape.attestationRefs,
  attestationDigests: GatewayCustodyProofPacketSchema.shape.attestationDigests,
  redactedAuditRefs: GatewayCustodyProofPacketSchema.shape.redactedAuditRefs,
  redactedAuditDigest: GatewayCustodyProofPacketSchema.shape.redactedAuditDigest,
  custodyDriftStatus: GatewayCustodyProofPacketSchema.shape.custodyDriftStatus,
  resolverDriftStatus: GatewayCustodyProofPacketSchema.shape.resolverDriftStatus,
  redactionStatus: GatewayCustodyProofPacketSchema.shape.redactionStatus,
  externalVerificationStatus: GatewayCustodyProofPacketSchema.shape.externalVerificationStatus,
  recordedAt: z.string().datetime({ offset: true }).optional(),
  expiresAt: z.string().datetime({ offset: true }),
});
export type RecordGatewayCustodyProofPacketInput = z.input<typeof RecordGatewayCustodyProofPacketInputSchema>;
