import { z } from "zod";
import { DigestSchema, IdSchema, IsoDateSchema, JsonValueSchema, ProtocolBaseSchema } from "../foundation/schema-core";

export const ContractStreamEventSchema = ProtocolBaseSchema.extend({
  streamEventId: IdSchema,
  streamId: IdSchema,
  streamScope: z.enum(["tenant", "organization", "run", "protected_surface_resource"]),
  offset: z.number().int().nonnegative(),
  partitionKey: z.string().min(1),
  eventType: z.enum([
    "intent_compiled",
    "runtime_execution_recorded",
    "generated_execution_graph_recorded",
    "protected_path_posture_recorded",
    "action_proposed",
    "policy_decision_recorded",
    "action_greenlit",
    "action_refused",
    "review_required",
    "review_artifact_recorded",
    "gateway_checked",
    "mutation_attempted",
    "protected_surface_operation_claimed",
    "protected_surface_operation_released",
    "surface_operation_reconciled",
    "gateway_refused",
    "review_decision_recorded",
    "breaker_decision_recorded",
    "receipt_emitted",
    "receipt_exported",
    "recovery_recommended",
    "recovery_status_changed",
    "proof_gap_recorded",
    "proof_gap_resolved",
    "isolation_changed",
  ]),
  eventTime: IsoDateSchema,
  producerRef: z.string().min(1),
  objectRefs: z.array(z.string().min(1)),
  previousEventDigest: DigestSchema.nullable(),
  eventDigest: DigestSchema,
  payload: z.record(z.string(), JsonValueSchema),
});
export type ContractStreamEvent = z.infer<typeof ContractStreamEventSchema>;
