import { z } from "zod";
import {
  DigestSchema,
  IdSchema,
  IsoDateSchema,
  ProtocolBaseSchema,
  ReasonCodeSchema,
  ResourceRefSchema,
  SignaturePostureSchema,
  SignatureSchema,
} from "../../foundation/schema-core";
import { RequiredProtectedPathStateSchema } from "../catalog-envelope/schemas";

export const PolicyDecisionValueSchema = z.enum([
  "greenlight",
  "refuse",
  "review_required",
  "halt",
  "quarantine",
  "proof_gap",
]);
export type PolicyDecisionValue = z.infer<typeof PolicyDecisionValueSchema>;

export const PolicyDecisionSchema = ProtocolBaseSchema.extend({
  policyDecisionId: IdSchema,
  actionContractId: IdSchema,
  envelopeId: IdSchema,
  policyPackRef: z.string().min(1),
  policyPackVersion: z.string().min(1),
  policyEvaluatorVersion: z.string().min(1),
  policyInputDigest: DigestSchema,
  decision: PolicyDecisionValueSchema,
  decisionReasonCode: ReasonCodeSchema,
  decisionReason: z.string().min(1).max(1000),
  matchedRuleIds: z.array(z.string()).default([]),
  requiredReceipt: z.enum(["none", "gate", "mutation", "downstream_finality"]),
  isolationSnapshotRef: z.string().min(1),
  expiresAt: IsoDateSchema,
  decisionSignature: SignatureSchema.nullable(),
  signaturePosture: SignaturePostureSchema,
  keyIdentityRef: z.string().min(1).nullable(),
  verificationPolicyRef: z.string().min(1).nullable(),
});
export type PolicyDecision = z.infer<typeof PolicyDecisionSchema>;

export const GreenlightSchema = ProtocolBaseSchema.extend({
  greenlightId: IdSchema,
  actionContractId: IdSchema,
  policyDecisionId: IdSchema,
  gatewayRegistryEntryId: IdSchema,
  gatewayRegistryDigest: DigestSchema.nullable().default(null),
  gatewayRegistryVersion: z.string().min(1),
  gatewayId: IdSchema,
  gatewayPolicyVersion: z.string().min(1),
  policyVersionRef: z.string().min(1).nullable().default(null),
  policyVersionDigest: DigestSchema.nullable().default(null),
  gatewayReadinessRef: z.string().min(1).nullable().default(null),
  gatewayReadinessDigest: DigestSchema.nullable().default(null),
  actionClass: z.string().min(1),
  resourceRef: ResourceRefSchema,
  requiredProtectedPathState: RequiredProtectedPathStateSchema,
  protectedPathPostureId: IdSchema.nullable(),
  protectedPathPostureDigest: DigestSchema.nullable(),
  gatewayCredentialRefIds: z.array(IdSchema).default([]),
  gatewayCredentialRefDigests: z.array(DigestSchema).default([]),
  delegatedAuthorityRefIds: z.array(IdSchema).default([]),
  delegatedAuthorityRefDigests: z.array(DigestSchema).default([]),
  paramsDigest: DigestSchema,
  contractDigest: DigestSchema,
  idempotencyKey: IdSchema.nullable().default(null),
  idempotencyLedgerKeyDigest: DigestSchema.nullable().default(null),
  maxUses: z.literal(1),
  issuedAt: IsoDateSchema,
  notBefore: IsoDateSchema,
  expiresAt: IsoDateSchema,
  isolationSnapshotRef: z.string().min(1),
  requiredReceipt: z.enum(["none", "gate", "mutation", "downstream_finality"]),
  decisionSignature: SignatureSchema.nullable(),
  signaturePosture: SignaturePostureSchema,
  keyIdentityRef: z.string().min(1).nullable(),
  verificationPolicyRef: z.string().min(1).nullable(),
  consumedAt: IsoDateSchema.nullable(),
  consumedByGateAttemptId: IdSchema.nullable(),
});
export type Greenlight = z.infer<typeof GreenlightSchema>;
